AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  StripeApiKey:
    Type: String
    Default: rk_test_51LsRYyAousYo8L0GPcSPZugK82dB2vp0IBBqWichYK3Vvmhvwxk8AQ0tHz3x7SpK931deEI7TNT03rsea90RtGWw00ALGE18bc
 
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  StripeEventWorkflowStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/stripe-event-workflow.asl.json
      DefinitionSubstitutions:
        StripeFunctionArn: !GetAtt Stripe.Arn
        PresignedUrlFunctionArn: !GetAtt PresignedUrl.Arn
        UpdatePresignedUrlFunctionArn: !GetAtt UpdatePresignedUrl.Arn
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref Stripe
        - LambdaInvokePolicy:
            FunctionName: !Ref PresignedUrl
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdatePresignedUrl
        - S3CrudPolicy:
            BucketName: website.sample-transcription-service
        - DynamoDBWritePolicy:
            TableName: purchase 
        - SESCrudPolicy:
            IdentityName: 'ito+test001@hugtech.io'

  Stripe:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stripe/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Environment:
        Variables:
          STRIPE_API_KEY: !Ref StripeApiKey
      Architectures:
        - x86_64

  PresignedUrl:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/presignedUrl/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
  UpdatePresignedUrl:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/updatePresignedUrl/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: website.sample-transcription-service
            FunctionName: !Ref UpdatePresignedUrl